"""add sinistro_fotos

Revision ID: 05929fdba139
Revises: c6810cc0d105
Create Date: 2026-01-14 12:35:28.090080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05929fdba139'
down_revision: Union[str, Sequence[str], None] = 'c6810cc0d105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sinistro_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SINISTRO', 'VITIMA', name='tipofoto'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('sinistro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sinistro_id'], ['sinistros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sinistro_fotos_id'), 'sinistro_fotos', ['id'], unique=False)
    op.drop_index(op.f('ix_fotos_id'), table_name='fotos')
    op.drop_table('fotos')
    op.alter_column('sinistros', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sinistros', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_table('fotos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.ENUM('SINISTRO', 'VITIMA'), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('caminho_arquivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('sinistro_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sinistro_id'], ['sinistros.id'], name=op.f('fotos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fotos_id'), 'fotos', ['id'], unique=False)
    op.drop_index(op.f('ix_sinistro_fotos_id'), table_name='sinistro_fotos')
    op.drop_table('sinistro_fotos')
    # ### end Alembic commands ###
