"""criacao_tabelas_iniciais

Revision ID: 4dfb329d64ec
Revises: 
Create Date: 2026-01-10 23:27:21.595039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfb329d64ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'AGENTE', name='perfilusuario'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('sinistros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_principal', sa.Enum('CARRO', 'MOTO', name='tipoprincipalsinistro'), nullable=False),
    sa.Column('tipo_secundario', sa.Enum('CARRO_CARRO', 'CARRO_MOTO', 'CARRO_PEDESTRE', 'CARRO_OUTRO', 'MOTO_CARRO', 'MOTO_MOTO', 'MOTO_PEDESTRE', 'MOTO_OUTRO', name='tiposecundariosinistro'), nullable=False),
    sa.Column('descricao_outro', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('ponto_referencia', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('houve_vitima_fatal', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sinistros_id'), 'sinistros', ['id'], unique=False)
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SINISTRO', 'VITIMA', name='tipofoto'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=False),
    sa.Column('sinistro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sinistro_id'], ['sinistros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_id'), 'fotos', ['id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CARRO', 'MOTO', 'OUTRO', name='tipoveiculo'), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('chassi', sa.String(length=17), nullable=True),
    sa.Column('descricao_outro', sa.String(length=255), nullable=True),
    sa.Column('sinistro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sinistro_id'], ['sinistros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_table('condutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condutores_id'), 'condutores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condutores_id'), table_name='condutores')
    op.drop_table('condutores')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_fotos_id'), table_name='fotos')
    op.drop_table('fotos')
    op.drop_index(op.f('ix_sinistros_id'), table_name='sinistros')
    op.drop_table('sinistros')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
