"""add latitude longitude to sinistros

Revision ID: 5266d09aa670
Revises: 05929fdba139
Create Date: 2026-01-14 20:42:21.729083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5266d09aa670'
down_revision: Union[str, Sequence[str], None] = '05929fdba139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sinistro_fotos', 'tipo')
    op.drop_column('sinistro_fotos', 'descricao')
    op.add_column('sinistros', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('sinistros', sa.Column('longitude', sa.Float(), nullable=False))
    op.alter_column('sinistros', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sinistros', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('sinistros', 'longitude')
    op.drop_column('sinistros', 'latitude')
    op.add_column('sinistro_fotos', sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('sinistro_fotos', sa.Column('tipo', mysql.ENUM('SINISTRO', 'VITIMA', collation='utf8mb4_unicode_ci'), nullable=False))
    # ### end Alembic commands ###
